### ISSUE TITLE
Problem CocoaPods SideMenuSwift

### ISSUE THREAD

**Issue by dromerobarria** [kukushi/SideMenu#1]
Unable to find a specification for `SideMenuSwift`

**Comment by kukushi** [comment]
@dromerobarria
`SideMenuSwift` is listing on https://cocoapods.org/?q=SideMenuswift.

Can you try `pod repo update master` before installing the dependency?

**Comment by dromerobarria** [comment]
My bad, you were totally right.
Thanks very much.
