### ISSUE TITLE
UISplitViewController not showing the Detail View

### ISSUE THREAD

**Issue by isaiasmac** [kukushi/SideMenu#10]
I have this code: 
`self.window = UIWindow(frame: UIScreen.main.bounds)`
`let splitViewController = UISplitViewController()`
`let navCtrl = UINavigationController(rootViewController: SecondVC())`
`splitViewController.viewControllers = [SideMenuController(contentViewController: navCtrl, menuViewController: ListMenuVC()), SecondChildVC()]`
`splitViewController.preferredDisplayMode = .allVisible`
`self.window!.rootViewController = splitViewController`
`self.window!.makeKeyAndVisible()`

When the app loads, the Detail View is not showing, I have to open the Side menu first.
The only quick is to call **revealMenu** and **hideMenu** methods:

`DispatchQueue.main.async {`
`            self.sideMenuController?.revealMenu(animated: false)`
`            self.sideMenuController?.hideMenu()`
`}`

**Comment by kukushi** [comment]
I have not yet tested on the `UISplitViewController` before. I will recommend you use the `SideMenuController` as the root view controller.

```swift
let sideMenu = SideMenuController(contentViewController: splitViewController, menuViewController: ListViewController())

window?.rootViewController = sideMenu
```

**Comment by kukushi** [comment]
@isaiasmac 

No warnings found on my side. It's my snippet for testing.

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        let splitViewController = UISplitViewController()
        let contentView = ContentViewController()
        let navCtrl = UINavigationController(rootViewController: contentView)
        splitViewController.viewControllers = [navCtrl, contentView]
        splitViewController.preferredDisplayMode = .allVisible
        
        let sideMenu = SideMenuController(contentViewController: splitViewController, menuViewController: ListViewController())
        
        window = UIWindow(frame: UIScreen.main.bounds)
        window?.rootViewController = sideMenu
        window?.makeKeyAndVisible()
        
        return true
    }
```
