### ISSUE TITLE
setContentViewController completion closure is loosing track of sideMenuController instance

### ISSUE THREAD

**Issue by dfabreguette-ap** [kukushi/SideMenu#100]
I stumbled upon a weird behavior, when you use "setContentViewController" completion closure outside of menu tableview controller (through segue SideMenu.Menu from a storyboard), you loose track of the sideMenuController instance as self instance refers to a controller that has no parent.

```swift
let sideMenuCtrl = sideMenuController // This is not nil !
sideMenuCtrl?.setContentViewController(with: "my-cached-controller", animated: true) {
  // But this is nil because self.parent is nil !
  // see https://github.com/kukushi/SideMenu/blob/0020966379a4b2a7c706608a8e2b62c6464806f1/Sources/SideMenu/UIViewController%2BSideMenu.swift#L22
  let sideMenuCtrl = sideMenuController
}
```
Is this normal ? If yes, then I think it should be mentioned any where in documentation.

Oh and by the way, this is a really nice plugin, I enjoyed working with it, and the cache feature is a really cool idea !

**Comment by kukushi** [comment]
You are correct. When `self` (current view controller) changes the parent side menu controller's content view controller to another view controller, `self` will be removed from the side menu controller, and it can no longer refer to the side menu controller. It's tricky but also expected.
I will update the documentation later.

**Comment by dfabreguette-ap** [comment]
Allright ! thanks @kukushi to get back

**Comment by kukushi** [comment]
Updated.
