### ISSUE TITLE
App crash when I try to assign Google map view to SlideMenuController contentview from scene delegate.

### ISSUE THREAD

**Issue by SalilLuley** [kukushi/SideMenu#108]
If user has not logged in then I navigate user to login view controller, but if user has already logged in then user is navigated to dashboard. On dashboard view I have set google maps view.
In Scene delegate I check user login and perform actions accordingly. In navigateToDashboard() method setting root view controller does not work with or without UINavigationController.

Application crashes while setting  viewController.view.frame = view.bounds  in load function of  SideMenuSwift

Below is my code

```swift
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
        // If using a storyboard, the `window` property will automatically be initialized and attached to the scene.
        // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
        guard let windowScene = (scene as? UIWindowScene) else { return }    
        window = UIWindow(frame: windowScene.coordinateSpace.bounds)
        window?.windowScene = windowScene
        window?.makeKeyAndVisible()
        //TODO:- Use this for ltr
        UIView.appearance().semanticContentAttribute = .forceLeftToRight
        
        if let token = UserDefaults.standard.value(forKey: ConstantUserDefaultKeys.token.rawValue) as? String, token.isEmpty {
            window?.rootViewController = UINavigationController(rootViewController: LanguageSelectionViewController())
        } else{
            navigateToDashboard()
        }
        
        
    }
    
    private func navigateToDashboard(){
        let contentViewController = DashboardViewController()
        let menuViewController = SlideMenuViewController()
        SideMenuController.preferences.basic.direction = .left
        SideMenuController.preferences.basic.enablePanGesture = true
        SideMenuController.preferences.basic.supportedOrientations = .portrait
        SideMenuController.preferences.basic.shouldRespectLanguageDirection = true
        window?.rootViewController =  SideMenuController.init(contentViewController: contentViewController, menuViewController: menuViewController)
        //window?.rootViewController = UINavigationController.init(rootViewController: SideMenuController.init(contentViewController: contentViewController, menuViewController: menuViewController))
    }
```

**Comment by kukushi** [comment]
@SalilLuley How is the crash stack trace look like?

**Comment by SalilLuley** [comment]
Crashes saying : EXC_BAD_ACCESS (code=1, address=0x5448540c) 

Crashes on Line
viewController.view.frame = view.bounds
in below code of sidemenuswift

extension UIViewController {

    func load(_ viewController: UIViewController?, on view: UIView) {
        guard let viewController = viewController else {
            return
        }

        // `willMoveToParentViewController:` is called automatically when adding

        addChild(viewController)

        viewController.view.frame = view.bounds
        viewController.view.translatesAutoresizingMaskIntoConstraints = true
        viewController.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]

        view.addSubview(viewController.view)

        viewController.didMove(toParent: self)
    }

    func unload(_ viewController: UIViewController?) {
        guard let viewController = viewController else {
            return
        }

        viewController.willMove(toParent: nil)
        viewController.view.removeFromSuperview()
        viewController.removeFromParent()
        // `didMoveToParentViewController:` is called automatically when removing
    }
}

**Comment by SalilLuley** [comment]
This bug is solved.
I was assigning mapview to view earlier.
No I added google mapview as a subview and assigned auto layout constraints and it worked seamlessly. Thank you for the help and creating such an awesome library.

Below is the code for anyones reference

view.addSubview(mapView)
        mapView.snp.makeConstraints { (make) in
            make.edges.equalToSuperview()
        }
