### ISSUE TITLE
Back button instead of menu

### ISSUE THREAD

**Issue by F4rid** [kukushi/SideMenu#11]
Hi
how i can add back button instead of menu button?!!!

i want when click to back button, come back to first page

**Comment by kukushi** [comment]
`SideMenu` don't have any limitations over how to reveal the menu.
For example, in a navigation controller, you can use a menu button as the left navigation item and it will automatically change to a back button when a new view controller is pushed.

**Comment by isaiasmac** [comment]
I'm using this as a subclass of all UIViewController in my project: 
```swift
class SideMenuSwiftViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let menuBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(openMenu))
        
        if let navCtrl = self.navigationController {
            
            if navCtrl.childViewControllers.count >= 2 {
                let backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: self, action: #selector(backButton))
                self.navigationItem.leftBarButtonItems = [menuBarButtonItem, backBarButtonItem]
            }
            else{
                self.navigationItem.leftBarButtonItems = [menuBarButtonItem]
            }
        }
    }
    
    @objc func openMenu() {
        self.sideMenuController?.revealMenu(animated: true)
    }
    
    @objc func backButton() {
        print("Back Button...")
        
        self.navigationController?.popViewController(animated: true)
    }

}

```

**Comment by Idomo** [comment]
@isaiasmac If you are using `NavigationViewController` so you'll get the `< back` button automatically when you'll perform some `Show` segue.
If you'll position the menu button on the left side (if you'r using LTR language) it will do the work for you.

**Comment by F4rid** [comment]
i looking for somthing like that
![slice](https://user-images.githubusercontent.com/19515037/42430232-264fad3a-8353-11e8-9adb-7793cbaf5d3b.png)

**Comment by kukushi** [comment]
@F4rid 
I don't know about your view controller hierarchy, but the action of the button is always under your control.

**Comment by F4rid** [comment]
@kukushi I'm really confused
i want to navigate between screen's when click on side menu items and just see side menu in home screen. 
consider i clicked on second item in side menu and i went to  testScreen. now i want to have a back button when click on it back to home screen.

**Comment by F4rid** [comment]
@kukushi 
thanks a lot but it not work! 
i already use this code but when i click on back button screen becomes black and not show any thing

**Comment by kukushi** [comment]
@F4rid 
Is the view controller properly initialized?

**Comment by F4rid** [comment]
@kukushi
yes

**Comment by kukushi** [comment]
@F4rid That's wired. Can you show me the code?

**Comment by F4rid** [comment]
@kukushi i use your example project, just in WorkWithOtherViewController.swift i add new back button to navigation bar and set action of that to `sideMenuController.contentViewController = ViewController`

**Comment by F4rid** [comment]
i solve this by adding navogation controller before side menu controller

**Comment by kukushi** [comment]
Sorry for the late reply.
Glad to see you solve it by yourself.
