### ISSUE TITLE
content not resizing with menuWidth

### ISSUE THREAD

**Issue by sriharsha-y** [kukushi/SideMenu#110]
Hello,

I don't know whether  its actually an issue with the library itself as the content in my TableViewController not get resized (width) when i set custom menuWidth for my menu. I have attached the screenshot for the same. I cross verified and all my constraints are correct. As you can see in below image the email id is not truncated which should happen when there is not enough width but thats not happening.

![Simulator Screen Shot - iPhone 5 - 2020-03-19 at 23 55 25](https://user-images.githubusercontent.com/28775722/77101722-c3dfe100-6a3d-11ea-9b20-00503e6b5c6a.png)

**Comment by kukushi** [comment]
It's a limitation of the library. The menu width is only allowed set before setup and the afterward changes will not work.
