### ISSUE TITLE
Swift 5.2 compiler error

### ISSUE THREAD

**Issue by lawgimenez** [kukushi/SideMenu#111]
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler:

**Comment by lawgimenez** [comment]
The workaround for now is that I set BUILD_LIBRARY_FOR_DISTRIBUTION = YES;

**Comment by kukushi** [comment]
@lawgimenez Is SideMenu integrated into your project using Carthage?

**Comment by lawgimenez** [comment]
I’m using cocoapods

**Comment by kukushi** [comment]
@lawgimenez It works fine in my environment. Did the error still happen?

**Comment by lawgimenez** [comment]
@kukushi I have not used this library anymore.
