### ISSUE TITLE
Left and right Menu

### ISSUE THREAD

**Issue by edon2005** [kukushi/SideMenu#12]
HI guys,

Is it possible to use one menu on the left side and another on the right ? 

Thanks

**Comment by kukushi** [comment]
I'm afraid not.
`SideMenu` is designed to have only one side menu view.

**Comment by edon2005** [comment]
Oh... It is sad... DO you plan to improve it ? :)

**Comment by kukushi** [comment]
I'm sorry but there is no plan to implement it.
Two side menu on both sides is rarely used in a real-world app.
