### ISSUE TITLE
Crashing on iOS 14.4

### ISSUE THREAD

**Issue by zeeshanTeks** [kukushi/SideMenu#126]
App is crashing on `setContentViewController` when `sideMenuController?.setContentViewController(with: "\(8)", animated: Preferences.shared.enableTransitionAnimation)` is called.

Error:

**Fatal error: [SideMenu] View controller associated with 8 not found!: file SideMenuSwift/SideMenuController.swift, line 583**

![Screenshot 2021-02-23 at 12 15 56 PM](https://user-images.githubusercontent.com/42762977/108810342-f04a9880-75d0-11eb-86c7-03591e3b7093.png)

**Comment by kukushi** [comment]
@zeeshanTeks Can you check if the `8` view controller has been cached?

**Comment by zeeshanTeks** [comment]
@kukushi : Yes the view controller is supposed to be cached. This works fine in lower versions, i.e., iOS 14.3 or lower.

**Comment by zeeshanTeks** [comment]
Apologise. This works fine. I was calling the incorrect view controller. It wasn't working on iOS 14.3 as well.
