### ISSUE TITLE
Support for Objective C

### ISSUE THREAD

**Issue by johnlpm** [kukushi/SideMenu#13]
I try to implement side menu on my objective c based project and it works fine on pan gesture. I create bridging header to call revealMenu method on a button , but it doesn't work ..

I double check the file and I see this line of code

```
  /// Access the nearest ancestor view controller hierarchy that is a side menu controller.
    public var sideMenuController: SideMenuController? {
        return findSideMenuController(from: self)
    }
    
    @available(*, deprecated, message: "Renamed to `sideMenuController`.")
    /// `SideMenu` currently doesn't support Objective-C, therefore the prefix was removed.
    public var sm_sideMenuController: SideMenuController? {
        return sideMenuController
    }
    
```

Please give me ideas to work on it.

**Comment by kukushi** [comment]
The ObjC is not supported now. I will add it when I have some free time.
PR is always welcomed.

**Comment by kukushi** [comment]
@johnlpm 
It turns out that if we want to port this framework to Objective-C, some Swift language needed to be disabled, like `struct`.  Thus, I decide not to support Objective-C and I will recommend you using some other Objective-C side menu alternatives or adding a Swift bridge inside your project.

**Comment by johnlpm** [comment]
@kukushi Thanks for quick response. I have try SWRevealViewController, but it was no longer maintained. That's why I look for swift based project and bridge it to my Obj-C based app.
Luckily, I look to your sample project and try this.
 @objc func menuButtonDidClicked(_ sender: Any) {
   
      ```
  let contentViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "ContentNavigation")
        let menuViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "MenuNavigation")
        let sideMenuController = SideMenuController(contentViewController: contentViewController, menuViewController: menuViewController)
        
//        sideMenuController?.revealMenu()
        UIApplication.shared.keyWindow?.rootViewController = sideMenuController
        sideMenuController.revealMenu()
    }
```

And it works fine now.
