### ISSUE TITLE
Please add steps for integration via SwiftPackageManager

### ISSUE THREAD

**Issue by PatilManoj1717** [kukushi/SideMenu#138]
Please add steps for integration via SwiftPackageManager

**Comment by kukushi** [comment]
Updated. Check the `Installation` section in the README.

**Comment by PatilManoj1717** [comment]
Thanks @kukushi for great work.

But I am getting following error while adding it via [Tuist](https://tuist.io)

error: Dependencies could not be resolved because root depends on 'swift-docc-plugin' 1.0.0..<2.0.0.
'swift-docc-plugin' >= 1.0.0 cannot be used because 'swift-docc-plugin' 1.0.0 contains incompatible tools version (5.6.0) and no versions of 'swift-docc-plugin' match the requirement 1.0.1..<2.0.0.
The 'swift' command exited with error code 1
