### ISSUE TITLE
Animate setContentViewController

### ISSUE THREAD

**Issue by Banck** [kukushi/SideMenu#14]
Hello!
It would be quite great if setContentViewController will be accompanied with animation.

**Comment by kukushi** [comment]
I did considered add some animation option on switching content view controller. As I planned, there will be some built in animations and custom animation which allow customization.

Which kind animation do you want?

**Comment by Banck** [comment]
There definitely should be fade in animation. And you can add somw other animation, like zoom, slide/cover, like push and etc. 

https://camo.githubusercontent.com/d1829c3cbb5e7c49b109e458ef95ec9079650d69/68747470733a2f2f63646e2e7261776769742e636f6d2f6c6b7a68616f2f4865726f2f656262336632632f5265736f75726365732f64656661756c74416e696d6174696f6e73322e737667

Thanks.

**Comment by kukushi** [comment]
Most works are done. You can try it on the `feature/transition-animation` branch.
It provides standard container view controller transition delegate method and a convenient class for adopting the built-in animation options.
