### ISSUE TITLE
Pan gesture is not working if side menu set to right side.

### ISSUE THREAD

**Issue by sumitaggarwalalgoworks** [kukushi/SideMenu#145]
Trying to open side menu by pan gesture if side menu is set to show from right side but it is not working, in case of left side it is working fine. Below are the properties that I have set

SideMenuController.preferences.basic.position = .above
SideMenuController.preferences.basic.direction = .right
SideMenuController.preferences.basic.enablePanGesture = true
SideMenuController.preferences.basic.supportedOrientations = .portrait
SideMenuController.preferences.basic.shouldRespectLanguageDirection = true

**Comment by MohitRanaTesting** [comment]
Hi

SideMenuController.preferences.basic.direction = .right

**Comment by sumitaggarwalalgoworks** [comment]
I am already using this code, Please check my first comment in which I have added all the settings.

**Comment by sumitaggarwalalgoworks** [comment]
Hi @MohitRanaTesting ,

Did you check?

**Comment by sumitaggarwalalgoworks** [comment]
I Was getting the issue because I was setting both direction and shouldRespectLanguageDirection.

**Comment by sumitaggarwalalgoworks** [comment]
I Was getting the issue because I was setting both direction and shouldRespectLanguageDirection.
