### ISSUE TITLE
Service Call

### ISSUE THREAD

**Issue by veer9002** [kukushi/SideMenu#15]
Hi, 
e.g., I have menu like 1,2,3,4,5.
When I select any option I got the container VC and service is Call only first time. I want service called everytime while select the option. Now, right now i have sync option if 5. So when I tap on 5 then service is called first time only. When I repeatedly tap on option 5 then No service is called.
Why? 

Thanks

**Comment by kukushi** [comment]
I’m sorry but I don’t know what you mean by service call.

**Comment by kukushi** [comment]
@veer9002 
According to your description, the service call is triggered from the menu. And in general case, the user is responsible for building the menu view controller, like the example app. I think maybe some condition prevent the service call from called again.

**Comment by veer9002** [comment]
Ok! Thank you so much for your quick replies.
