### ISSUE TITLE
Menu not displayed as expecting

### ISSUE THREAD

**Issue by fredericdnd** [kukushi/SideMenu#16]
Hello,

First, thanks for your library !

I'm encountering an issue with the menu. It is embedded in a navigation controller and contains a segmented control and a table view. The menu is width `UIScreen.main.bounds.width - 44.0`, but the menu seems to be 375 pixels large (the width of my iPhone screen).

<img src="https://user-images.githubusercontent.com/14300551/44212591-03f92680-a16c-11e8-8d67-d8a513032ca2.png" width="250">

What can be the reason for this problem?

Thanks for your help.

**Comment by kukushi** [comment]
Do you setting the width of side menu before it’s initialized?

**Comment by fredericdnd** [comment]
Indeed, the preferences were not set before SideMenuController was initialized, but this not resolved the problem.

**Comment by fredericdnd** [comment]
The SideMenuController preferences are set up in the AppDelegate. Right after setting up theses preferences, I set the window rootViewController to my SideMenuController.

The contentViewController and the menuViewController are both set up in a storyboard, is there something special to do when we use storyboards with SideMenuController ?

**Comment by kukushi** [comment]
The setup seems fine while I have never do it that way. I will try it.

**Comment by fredericdnd** [comment]
Thanks for your help, I will continue to search a solution.

**Comment by fredericdnd** [comment]
Hey ! I found a solution by adding a left constraint to the menu :

<img src="https://user-images.githubusercontent.com/14300551/45424028-80acf100-b695-11e8-9bb6-14f242769604.png" width="250">

**Comment by tulioccalazans** [comment]
@fredericdnd answer should be in the library documentation!

**Comment by rursache** [comment]
@fredericdnd's solution is not ideal, try embedding a navigationController in your menu and see how navBar is not scaled..

**Comment by robertofrontado** [comment]
Solution far from ideal 😕
