### ISSUE TITLE
statusBar 不恰当隐藏

### ISSUE THREAD

**Issue by listenzz** [kukushi/SideMenu#2]
当 menu direction 为 left 时，在右边沿滑动，状态栏会隐藏，松开手后复原，当  menu direction 为 right 时，在左边沿滑动也一样。

**Comment by kukushi** [comment]
@listenzz 
开发的时候，测试下来发现滑动开始的时候是比较好的改变状态栏的时机。看了市面上的应用，Bear 也是这么处理的，也比较自然。

你是觉得哪里不恰当吗？

**Comment by listenzz** [comment]
比如 side menu 在左边，在左边沿往右滑动时，可以隐藏状态栏，但是从右边沿往左滑时，我认为不应该隐藏状态栏，因为此时右边并没有 menu。

**Comment by kukushi** [comment]
@listenzz 
哦，确实。这是一个 BUG。

**Comment by kukushi** [comment]
@listenzz 
修好了，提交在了 develop 分支。如果有时间的话可以看下。
感谢你的反馈。

**Comment by listenzz** [comment]
@kukushi 👌，已无此问题
