### ISSUE TITLE
Push Controller from side menu

### ISSUE THREAD

**Issue by zeinab-reda** [kukushi/SideMenu#20]
how can push view controller from side menu ? it's only presenting it !!

**Comment by kukushi** [comment]
Use the Navigation controller as the content view controller, you can push a child view controller into the navigation stack.

**Comment by zeinab-reda** [comment]
i do as in example that but cannot push controller from side menu :/

**Comment by zeinab-reda** [comment]
like that 
" self.navigationController?.present(SideMenuController(contentViewController: UINavigationController(rootViewController: HomeViewController.create()),menuViewController: ClientSideMenuTableViewController.create()), animated: true, completion: nil)  "

**Comment by kukushi** [comment]
What you want is to push a SideMenuController?

**Comment by Edwin-iter** [comment]
I have the same problem! I need to push another view controller. This is my example (button on the menu): "self.navigationController?.pushViewController(HistoryVC(), animated: true)"

**Comment by kukushi** [comment]
@zeinab-reda @kukushi Can you provide a simple demo?

**Comment by UzumakiAlfredo** [comment]
I have this problem too!

I want to push to another controller when I am on one of contentViewControllers of the side menu.

**Comment by kukushi** [comment]
@UzumakiAlfredo 
Asses the content view controller then do anything you want.
```swift
        guard let navigationController = sideMenuController?.contentViewController as? UINavigationController else {
            return
        }
        navigationController.pushViewController(HistoryVC(), animated: true)
```

**Comment by gourav06111993** [comment]
how can i reveal sidemenu in child viewcontroller

sidemenu option1-> push option1 view controller -> push to child controller -> show side menu in child controller

**Comment by kukushi** [comment]
@gourav06111993 
You can call `sideMenuController.revealMenu()` in any child view controller to reveal the menu.
