### ISSUE TITLE
Programatic example

### ISSUE THREAD

**Issue by Smiller193** [kukushi/SideMenu#22]
I see stroyboard everywhere but I see no programatic example. Can anyone point me in the direction of now

**Comment by kukushi** [comment]
Check it here.
https://github.com/kukushi/SideMenu/blob/bfdf97a206ce825711262c63fd889442d5545b02/Example/OtherExampleViewController.swift#L28

**Comment by Smiller193** [comment]
yeah so im lost do i have to create my own menu controller and what is the content view controller

**Comment by kukushi** [comment]
Yes. It's described in the Readme.

 To start the app with `SideMenu` programmatically:
import UIKit
import SideMenuSwift
// If you are using Carthage, uses `import SideMenu`

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    @objc func applicationDidFinishLaunching(_ application: UIApplication) {
        let contentViewController = ...
        let menuViewController = ...

        window = UIWindow(frame: UIScreen.main.bounds)
        window?.rootViewController = SideMenuController(contentViewController: contentViewController, 
        menuViewController: menuViewController)
        
        window?.makeKeyAndVisible()
        return true
    }
}

**Comment by Smiller193** [comment]
oh okay that makes sense

**Comment by Smiller193** [comment]
im going to try and do that right now and let you know how it goes

**Comment by Smiller193** [comment]
okay it seems to be working however when I display the view controller for some reason it is messed up

**Comment by Smiller193** [comment]
upgraded to xCode10 and menu just wont show any more

**Comment by Smiller193** [comment]
there is an issue the first time I run the app it never presents the sidemenu

**Comment by kukushi** [comment]
@Smiller193 It works fine on my own usage. How to reproduce it?

**Comment by Smiller193** [comment]
I mean i don't do anything special I follow the tutorial for the most part. This is how i configure it in my appdelegate.



        func configureInitialRootViewController(for window: UIWindow?) {
           // print("Look for current user here")
           // print(Auth.auth().currentUser ?? "")
             UserDefaults.standard.set(false, forKey: UserDefaultsKeys.isFirstIntro.rawValue)
            let defaults = UserDefaults.standard
            var initialViewController: UIViewController
                NotificationCenter.default.addObserver(self, selector: #selector(handleHeartAttack), name: heartAttackNotificationName, object: nil)
           // print(Auth.auth().currentUser ?? "")
            if Auth.auth().currentUser != nil,
                let userData = defaults.object(forKey: "currentUser") as? Data,
                let user = NSKeyedUnarchiver.unarchiveObject(with: userData) as? User {
                
                User.setCurrent(user, writeToUserDefaults: true)
               // print("root view controller set to home view controller")
                let contentViewController = HomeViewController()
                let menuViewController = MenuViewController()
                
                SideMenuController.preferences.basic.menuWidth = 215
                SideMenuController.preferences.basic.position = .sideBySide
                SideMenuController.preferences.basic.statusBarBehavior = .none
                SideMenuController.preferences.basic.direction = .right
                SideMenuController.preferences.basic.supportedOrientations = .portrait
                SideMenuController.preferences.basic.shouldRespectLanguageDirection = true
                SideMenuController.preferences.basic.defaultCacheKey = "home"
    
                initialViewController = SideMenuController(contentViewController: contentViewController, menuViewController: menuViewController)
    
                
            } else {
               // print("root view controller set to login view controller")
                initialViewController = LoginViewController()
            }
            window?.rootViewController = initialViewController
            window?.makeKeyAndVisible()
            revealingSplashView.animationType = .heartBeat
            window?.addSubview(revealingSplashView)
            revealingSplashView.startAnimation()
            
        }


Then I set it up

    
    import UIKit
    import SideMenuSwift
    
    class MenuViewController: UIViewController {
        let cellID = "cellID"
        let headerID = "headerID"
    
        let sideMenuTableView: UITableView = {
            let sideMenuTableView = UITableView(frame: CGRect.zero, style: .grouped)
            sideMenuTableView.backgroundColor = .white
            sideMenuTableView.separatorStyle = .none
            sideMenuTableView.showsVerticalScrollIndicator = false
            return sideMenuTableView
        }()
        let footer = MenuFooter()
        
        override func viewDidLoad() {
            super.viewDidLoad()
            configureView()
            // Do any additional setup after loading the view.
        }
        
        @objc func configureView(){
            view.backgroundColor = .white
            view.addSubview(sideMenuTableView)
            view.addSubview(footer)
            sideMenuTableView.delegate = self
            sideMenuTableView.dataSource = self
            sideMenuTableView.snp.makeConstraints { (make) in
                make.top.equalTo(view.safeAreaLayoutGuide.snp.top)
                make.left.right.equalTo(view.safeAreaLayoutGuide)
                make.height.equalTo(view.bounds.height *  (3.50 / 4))
            }
            footer.snp.makeConstraints { (make) in
                make.top.equalTo(sideMenuTableView.snp.bottom)
                make.left.right.equalTo(view.safeAreaLayoutGuide)
                make.bottom.equalTo(view.safeAreaLayoutGuide.snp.bottom)
            }
            
            registerCells()
        }
        
        @objc func registerCells(){
            sideMenuTableView.register(MenuHeader.self, forCellReuseIdentifier: headerID)
            sideMenuTableView.register(MenuCell.self, forCellReuseIdentifier: cellID)
            footer.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(self.presentSettings)))
        }
    
        @objc func presentSettings(){
            self.sideMenuController?.hideMenu()
            let settingView = SettingsViewController()
            let settingsNav = UINavigationController(rootViewController: settingView)
            sideMenuController?.contentViewController = settingsNav
        }
        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }
    
    }
    
    extension MenuViewController: UITableViewDelegate{
        func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
            return 50
        }
        
        func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
            return 45
        }
    }
    
    
    extension MenuViewController: UITableViewDataSource{
        func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
            return 3
        }
        
        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
            let cell = tableView.dequeueReusableCell(withIdentifier: cellID, for: indexPath) as! MenuCell
            cell.nameLabel.text = "Option"
            return cell
        }
        
        func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
            let cell = tableView.dequeueReusableCell(withIdentifier: headerID) as! MenuHeader
            return cell
        }
        
    
        
        
    }


Then I present it like this

    //will present the dropdown/side menu
    @objc func rightBarPressed(){
        print("right bar tapped")
        self.sideMenuController?.revealMenu(animated: true, completion: nil)
    }

**Comment by Smiller193** [comment]
Typically when i first open the app it doesn't work but if i close it and reopen it works

**Comment by DusanEastcode** [comment]
I have also the problem first time app is installed. It takes 10 seconds to show up the menu. UIApplication.shared.keyWindow?.rootViewController = sideMenuController this part  takes 10 seconds to accomplish.
