### ISSUE TITLE
Add shadow to ViewController

### ISSUE THREAD

**Issue by FominNickolai** [kukushi/SideMenu#27]
Hi guys, is it possible to add shadow to ViewController when menu position is SideBySide?
![ios-simulator-screen-shot-11-aug-2014-13 46 34](https://user-images.githubusercontent.com/11337735/49871311-80e89400-fe1e-11e8-919d-33bd381015fa.png)

**Comment by kukushi** [comment]
The shadow was removed as design.
When using `sideBySide`, the two views are at the same level, thus there is no shadow.
