### ISSUE TITLE
Slow first time menu is revealed with subviews added

### ISSUE THREAD

**Issue by suhfang** [kukushi/SideMenu#29]
Hi all,

I just added SideMenu's cocoa pod to mySwift 4.2 iOS project. I followed the documentation to the latter. 

The experience I have is the fist time I call `sideMenuController.revealMenu()` is that it's  really slow when views have been added on the `sideMenuController`.  It  works smoothly afterwards. It tried calling this function asynchronously thinking it could work, but nothing improved. Everything works smoothly all time when the `sideMenuController` has little or no views added unto it. 

I don't know if anyone experienced this. Any help would be appreciated.

Thanks

**Comment by kukushi** [comment]
@suhazinwi 
I think you may have put some heavy work on the `viewDidLoad()` or `init()` of the menu/content view controller, which will slow down the side menu.

**Comment by kukushi** [comment]
There must be some time consuming operation during the first revealing, the time profiler instrument may help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
