### ISSUE TITLE
Sidemenu direction is not working properly first time in arabic language(RTL)

### ISSUE THREAD

**Issue by SimbuCA** [kukushi/SideMenu#30]
I changed the language in appdelegate to arabic. The menu icon in the navigation bar changed to right side is fine. When clicking on the menu icon, the side menu shows in left side with misaligned. I run second time its working fine. I am using to change language to arabic using https://github.com/Abedalkareem/LanguageManager-iOS.

**Comment by kukushi** [comment]
Any follow up？@SimbuCA

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IbRoHiM-IUT** [comment]
I have a same error. Sidemenu direction is not working properly with arabic language. The navigation bar's menu icons changed. But when i press on either left menu icon or right one, the side menu shows in different sides. if I run app, it's working fine. can you help me to fix?

**Comment by codeaegisit** [comment]
@kukushi I'm facing the same issue again. Is their any solution for this ?

**Comment by codeaegisit** [comment]
I've pushed the solution for the same already. Not sure if this has been merged or not

**Comment by codeaegisit** [comment]
> I'm facing the same issue, is there any solution for this?

I've pushed the solution for the same already. Not sure if this has been merged or not

**Comment by kukushi** [comment]
@codeaegisit 's solution had been merged in 2.0.8. @vijaycoderkube Can you elaborate how to produce this issue?
