### ISSUE TITLE
Bug When inherit UINavigationController

### ISSUE THREAD

**Issue by FerryAWijayanto** [kukushi/SideMenu#31]
I try to make sideMenuController have a navigation, but when I try to swipe the menu. navigation controller being pushed down and my navigation title not showing.

**Comment by kukushi** [comment]
Sorry, I can't figure out how you use side menu. Sample code or detailed description may help.

**Comment by FerryAWijayanto** [comment]
hey kukushi i receive your email, I give you my code how I use sideMenu.


I make a function to generate a navigation controller like this.


func generateNavController(with rootViewController: UIViewController, title: String, image: UIImage) -> UIViewController {

        let navController = StatusbarNavController(rootViewController: rootViewController)

        navController.tabBarItem.title = title

        navController.tabBarItem.image = image



        return navController

    }

this is my status bar class


class StatusbarNavController: UINavigationController {

    override var preferredStatusBarStyle: UIStatusBarStyle {

        return .lightContent

    }

}

and I passed in my function like this


generateNavController(with: SlideMenuController(mainViewController: ChatController(), leftMenuViewController: MenuController()), title: "Chat", image:  imageLiteral(resourceName: "icons8-chat-50"))

and when I try to swipe the menu the navigation being push down.

________________________________

**Comment by kukushi** [comment]
I will suggest you using side menu controller as the top most view controller
