### ISSUE TITLE
Tabbed Bar Views open Menu by a Navigation Left Item Problem

### ISSUE THREAD

**Issue by behaxe** [kukushi/SideMenu#4]
Thank you for this awesome framework.
I have just use it in a project, and here is my problem.
I'm using this hierarchy. Navigation Controller --> TabBarController --> Three TabbedBarViews.

I have the same navigation menu button for all my tabbed bars, but i have to instantiate as initial Controller my Navigation Controller. 
When I try to appear the menu from my second or my third view by clicking on this button, this is showed but the backView of the menu is changed to my FirstTabController.
I don't have this issue when I swipe right to show it. I mean i can show it correctly by swipping, but not by clicking on the button.

Hope you have any idea. If you need I can send you an image for the aproximation.

**Comment by kukushi** [comment]
Sure. A screenshot will be helpful.

**Comment by behaxe** [comment]
Here is my hierarchy : 
![captura de pantalla 2018-06-18 a las 7 33 40](https://user-images.githubusercontent.com/32493617/41519801-80ef2cd2-72ca-11e8-8767-5a4e91a3cbf2.png)


Here is the code im trying to use.  The starting controller should be the navigation controller, to show correctly the Tab Bar and the Navigation bar.

![captura de pantalla 2018-06-18 a las 7 34 18](https://user-images.githubusercontent.com/32493617/41519826-bbab3ffa-72ca-11e8-8b0d-85a9985dc3e5.png)

**Comment by kukushi** [comment]
@behaxe I'm afraid you're not using this framework in the right way.
If you prefer the storyboard approach, I would recommend you read the **Usage-Storyboard** part of the README once again.
Meanwhile, you should not put the `let contentViewController ...` calls inside the menu action. The menu action is triggered every time the button is tapped, thus the `sideMenuController.revealMenu()` should be sufficient.

**Comment by behaxe** [comment]
@kukushi thank you for your answer, you were totally rigth. I was declaring in a wrong place the ContentViewController and the startingView.
Thanks for your time contributing to the Swift Devs! 👍 💯

**Comment by kukushi** [comment]
@behaxe If you have any other problem, feel free to let me know.
