### ISSUE TITLE
Side menu pan gesture overrides tableview's cell swipe gesture

### ISSUE THREAD

**Issue by teo029** [kukushi/SideMenu#41]
I think the menu's gesture should be a Screen Edge Pan, not a classic pan. I want to swipe over my tableview's cell and it triggers the sliding menu, even from the middle of the screen.

I will disable the pan gesture in this screen, but I think a better solution is needed.

**Comment by teo029** [comment]
Overall, the pan gesture does not work as intended. You sometimes can't swipe the screen. I think the screen should be visible only on

**Comment by kukushi** [comment]
Gesture collision is hard to rule out. The screen edge pan may reduce the chance of collision but won't sovle the problem.
