### ISSUE TITLE
basic.position = .under 时主视图变暗没有过渡动画

### ISSUE THREAD

**Issue by the-1000th-summer** [kukushi/SideMenu#44]
1.如题，我的side menu 在左边，刚向右划，主视图突然变暗，而不是逐渐变暗（提供的示例程序也是这样子），basic.position = above 和 sideBySide 则没有此问题。
2.顺便请问一下在划出side menu时能否不让主视图变暗？

3.关于已经关闭的问题 Position with .under will be full screen #36 我也同样遇到了此问题，在用代码而不用 Storyboard 创建side menu controller时会这样
![a](https://user-images.githubusercontent.com/26242253/54696814-75b4ab00-4b67-11e9-86e6-28f28f403806.gif)
storyBoard:
![屏幕快照 2019-03-20 23 22 52](https://user-images.githubusercontent.com/26242253/54696877-95e46a00-4b67-11e9-9b6e-276e2e446f49.png)

**Comment by kukushi** [comment]
感谢反馈，我会看下。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kukushi** [comment]
@the-1000th-summer 能否提供一个  Demo？

**Comment by the-1000th-summer** [comment]
@kukushi 
第3个问题：
[Test4.zip](https://github.com/kukushi/SideMenu/files/3000067/Test4.zip)

第1个问题：
![IMG_8064 TRIM](https://user-images.githubusercontent.com/26242253/54875361-9cf5cb80-4e38-11e9-8ff3-e860ed29feb0.gif)

**Comment by kukushi** [comment]
第三个问题是因为部分属性需要在 SideMenu 初始化之前设定：

```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        let contentViewController = storyboard.instantiateViewController(withIdentifier: "MainNav")
        let menuViewController = storyboard.instantiateViewController(withIdentifier: "LeftNav")
        
        SideMenuController.preferences.basic.menuWidth = 240
        SideMenuController.preferences.basic.position = .under

        let sideMenuCon = SideMenuController(contentViewController: contentViewController, menuViewController: menuViewController)

        window = UIWindow(frame: UIScreen.main.bounds)
        window?.rootViewController = sideMenuCon

        window?.makeKeyAndVisible()
        return true

    }
```

position 为 under 的阴影已经去掉了，第一和第二个问题也解决了，可以用最新的 commit 试一下。

**Comment by the-1000th-summer** [comment]
问题解决了，感谢。
