### ISSUE TITLE
sidemenu not push and pop view controller from sidemenu options

### ISSUE THREAD

**Issue by jignesh-stratecore** [kukushi/SideMenu#45]
sidemenu not push and pop view controller from sidemenu options

**Comment by kukushi** [comment]
@jignesh-stratecore Can you provide a more detailed description?

**Comment by jignesh-stratecore** [comment]
I will share steps if possible.

Suppose we have multiple options in side menu. And user need to go next
pushed view controller from side menu. So we call the navigation controller
pushviewcontroller method.

When user come back from pushed viewcontroller then issue generate!! The
navigation control changed from previous. I checked the pod code but not
getting any idea how to solve this problem.

**Comment by kukushi** [comment]
I think you may be call methods on different navigation controller. I would suggest you double checking the navigation controller you are calling methods on.

Xing He,
Best Regards

**Comment by jignesh-stratecore** [comment]
suppose if we have to switch the content view controller then we use code like below

```
// Switch to it when needed
sideMenuController?.setContentViewController(with: "second")
```

instead of switch view controller, we need to push and pop the view controller then any idea what to do?

**Comment by kukushi** [comment]
There are many approaches to achieve that.
The easiest way is let the menu controller hold a reference to the content view controller's navigation controller when setup the side menu. Then you can push & pop on that navigation controller from the menu controller.

**Comment by JhonnyTawk** [comment]
How to achieve that can you provide an example?
