### ISSUE TITLE
how can clear selected item highlight ?

### ISSUE THREAD

**Issue by mahmooddagga** [kukushi/SideMenu#46]
how can clear selected item highlight ?

because of  i show popup dialog in "  didSelectRowAt " but still highlighted after press

    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {

**Comment by mahmooddagga** [comment]
@kukushi

**Comment by kukushi** [comment]
@mahmooddagga 
Generally, I think it's out of scope of Side Menu.
StackOverflow would be a better place for this kind of problem.
