### ISSUE TITLE
first time menu not show after login 

### ISSUE THREAD

**Issue by knight6700** [kukushi/SideMenu#49]
after login menu not show how to show menu when pressed in login button

        if UserDefaults.standard.string(forKey: "id") != nil {
            let story = UIStoryboard(name: "Main", bundle: nil)
            let side = UIStoryboard(name: "SideMenu", bundle: nil)
            window?.rootViewController = SideMenuController(contentViewController: story.instantiateInitialViewController()!, menuViewController: side.instantiateInitialViewController()!)
            SideMenuController.preferences.basic.menuWidth = 240
            SideMenuController.preferences.basic.statusBarBehavior = .hideOnMenu
            SideMenuController.preferences.basic.position = .sideBySide
            SideMenuController.preferences.basic.direction = .left
            SideMenuController.preferences.basic.enablePanGesture = true
            SideMenuController.preferences.basic.supportedOrientations = .portrait
            SideMenuController.preferences.basic.shouldRespectLanguageDirection = true
            window?.makeKeyAndVisible()
        } else {
            let story = UIStoryboard(name: "Login", bundle: nil)
            window?.rootViewController = story.instantiateInitialViewController()
            window?.makeKeyAndVisible()
        }

**Comment by iarshad20** [comment]
@knight6700 you just need to copy the whole code after if condition and paste it in the Login Button Action. You have to specify rootViewController that's all.

**Comment by knight6700** [comment]
@iarshad20 i did it but no thing changed

**Comment by kukushi** [comment]
@knight6700 
First, you need to setup the side menu before it's initialized, like:

```swift
    let story = UIStoryboard(name: "Main", bundle: nil)
        let side = UIStoryboard(name: "SideMenu", bundle: nil)
        SideMenuController.preferences.basic.menuWidth = 240
        SideMenuController.preferences.basic.statusBarBehavior = .hideOnMenu
        SideMenuController.preferences.basic.position = .sideBySide
        SideMenuController.preferences.basic.direction = .left
        SideMenuController.preferences.basic.enablePanGesture = true
        SideMenuController.preferences.basic.supportedOrientations = .portrait
        SideMenuController.preferences.basic.shouldRespectLanguageDirection = true
        window?.rootViewController = SideMenuController(contentViewController: story.instantiateInitialViewController()!, menuViewController: side.instantiateInitialViewController()!)
        window?.makeKeyAndVisible()
```

Second, the menu won't show by default, you need to reveal it manually.
