### ISSUE TITLE
How to pass data from sidemenucontroller to contentviewcontroller

### ISSUE THREAD

**Issue by iamdeadman** [kukushi/SideMenu#50]
Hi, 

I have created a root ContentViewController for my main view and a NavigationViewController for the sidemenu. 
I am trying to launch the screen as suggested in readme like this - 

```
let nav = NavigationViewController.createViewController()
        window.rootViewController = SideMenuController(contentViewController: viewController, menuViewController: nav)
        
        window.makeKeyAndVisible()
```

where viewController is my ContentViewController and nav is my NavigationViewController

Now in my viewController I can do 

```
@IBAction func onClickMenu(_ sender: Any) {
        menuVisible = !menuVisible
        if menuVisible {
            sideMenuController?.revealMenu()
        } else {
            sideMenuController?.hideMenu()
        }
    }
```

Now, how can I pass data from menu controller to my content view controller for example if I have a array list of menu items displayed in my menu controller and I want to pass the currently selected menu item to this content view controller. Is this possible ? if so can you please show me how this can be done or can you point me to a example that does the same

**Comment by kukushi** [comment]
You can pass data to the `contentViewController` when switching like: https://github.com/kukushi/SideMenu/blob/df7552166ea1aeb6d72df0d01ae9f2e5d7fa4217/Example/MenuViewController.swift#L132
