### ISSUE TITLE
implementation with UITabBarscontroller ?

### ISSUE THREAD

**Issue by ghimireprashant** [kukushi/SideMenu#51]
how to implement side menu with tabbar controller and also how to push view controller while click from side menu

**Comment by kukushi** [comment]
First of all, you need to set SideMenuController as the Root view controller. The architecture is:
- SideMenuController
     - TabBarController
        - NavigationController

In order to push view controller when clicking on the menu, you need to let the menu controller hold the reference to navigation controller.
