### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by mohit2305** [kukushi/SideMenu#53]
My app is portrait for iPhone and landscape for iPad. It is crashing on

Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [SideMenuSwift.SideMenuController shouldAutorotate] is returning YES'

I am using storyboard and my storyboard file is different for iPhone and iPad

**Comment by kukushi** [comment]
@mohit2305 Hi, can you provide demo or code to reproduce this crash?

**Comment by boardmain** [comment]
sample problem
if you set the app only for landscape it crash
