### ISSUE TITLE
Present SideMenu from a Login screen

### ISSUE THREAD

**Issue by vdphong** [kukushi/SideMenu#54]
Hi @kukushi, 
I have a login screen, how can I present SideMenuViewController after user click on login button. 
Code: 
let storyboard = UIStoryboard.init(name: "Main", bundle: nil) 
let viewController = storyboard.instantiateViewController(withIdentifier: "SideMenuViewController") as! ???
viewController.user = user (I need to pass this user object to SideMenuViewController)

Appreciate your help!

**Comment by vdphong** [comment]
> Hi @kukushi,
> I have a login screen, how can I present SideMenuViewController after user click on login button.
> Code:
> let storyboard = UIStoryboard.init(name: "Main", bundle: nil)
> let viewController = storyboard.instantiateViewController(withIdentifier: "SideMenuViewController") as! ???
> viewController.user = user (I need to pass this user object to SideMenuViewController)
> 
> Appreciate your help!

I had found a solution!

**Comment by karthisiva** [comment]
share sample project of this others can get benefit.

**Comment by Adakhan** [comment]
> > Hi @kukushi,
> > I have a login screen, how can I present SideMenuViewController after user click on login button.
> > Code:
> > let storyboard = UIStoryboard.init(name: "Main", bundle: nil)
> > let viewController = storyboard.instantiateViewController(withIdentifier: "SideMenuViewController") as! ???
> > viewController.user = user (I need to pass this user object to SideMenuViewController)
> > Appreciate your help!
> 
> I had found a solution!

Please^ share your solution!
