### ISSUE TITLE
Push ViewController from App Delegate

### ISSUE THREAD

**Issue by SimbuCA** [kukushi/SideMenu#55]
I have implemented the application using this side menu. The navigation flow is working fine. I am trying to build an application like banking application. If user idles for 15 minutes it redirected(push) to the login page. Once the user login, it back to the corresponding page. The timer running in the extension of UIApplication. I am trying to push the login view controller from the extension of UIApplication. 

I am using this code to push from the extension of UIApplication

```
let rootViewController = self.window!.rootViewController as! UINavigationController
    let mainStoryboard = UIStoryboard(name: "Main", bundle: nil)
    let profileViewController = mainStoryboard.instantiateViewController(withIdentifier: "InstructionVC") as! InstructionVC
    rootViewController.pushViewController(profileViewController, animated: true)
```

But I am getting this error

`

> Could not cast value of type SideMenuSwift.SideMenuController to UINavigationController

`

**Comment by kukushi** [comment]
You need to call push from the navigation controller. In your case, maybe the `contentViewController`.
