### ISSUE TITLE
Menu Under (not below)

### ISSUE THREAD

**Issue by EduardoGin** [kukushi/SideMenu#56]
Hello,

How can I put the Menu to appear say under the Navigation bar for instance?

I did this (see attachment) but all it does it push the content down, not the whole view.
I understand part of this is because you set the Menu on a whole view.

Any way to go around this?
![Simulator Screen Shot - iPhone Xs - 2019-04-30 at 15 25 38](https://user-images.githubusercontent.com/47526850/56969483-2c3f7e80-6b5d-11e9-802b-f836eaa77386.png)

**Comment by kukushi** [comment]
There is no known workaround. Maybe you can do some trick to tweak that.

**Comment by EduardoGin** [comment]
@kukushi thanks :)

Yeah, I will look into it.

Any progress I will let you know
