### ISSUE TITLE
Navigation Bar disappears

### ISSUE THREAD

**Issue by EduardoGin** [kukushi/SideMenu#57]
Hello,

Everything is presenting as it should and working, apart from this last bit:

I lose my UINavigation Bar if I segue to another VC via the menu.
See attachment

![56954791-aa892a00-6b37-11e9-8e14-6ef0563a534d](https://user-images.githubusercontent.com/47526850/57020743-2790ce00-6c22-11e9-9231-e3c13627a4a7.png)
![Screenshot 2019-05-01 at 15 02 58](https://user-images.githubusercontent.com/47526850/57020765-3e372500-6c22-11e9-81d7-4eefd4ea83ee.png)

Any ideas on this?
Thanks :)

**Comment by kukushi** [comment]
Nope.
