### ISSUE TITLE
Safe area insets on landscape mode

### ISSUE THREAD

**Issue by anelad** [kukushi/SideMenu#58]
Missing safe area insets both for side and main views on portrait mode (for iPhone X <)

![Screen Shot 2019-05-07 at 14 48 18](https://user-images.githubusercontent.com/5767654/57297042-3cb0a580-70d7-11e9-93b2-92fcae904008.png)

**Comment by anelad** [comment]
For a quick workaround use this:

```
override func viewWillLayoutSubviews() {
    SideMenuController.preferences.basic.menuWidth = 240 + self.view.safeAreaInsets.left
}
```

**Comment by kukushi** [comment]
@anelad 
The solution is correct.
Safe area (for side menu) is only needed for part of the users, and they can archive that without much effort.
