### ISSUE TITLE
Is it possible to navigate to a special tab bar item?

### ISSUE THREAD

**Issue by behaxe** [kukushi/SideMenu#6]
Hello there again, im continuing using your great framework.
I have found an issue in my project. I want to move from an imageTapped in the SideMenu, but Im only able to present my startingViewController(FirstView, with his own navigationController and TabBarController as FatherViews)

Do you think it is possible? Can you give me any idea?
Thanks for your time.

![captura de pantalla 2018-06-29 a las 12 56 45](https://user-images.githubusercontent.com/32493617/42089009-ea5342f6-7b9b-11e8-8494-1386d41ba98f.png)

**Comment by kukushi** [comment]
I'm sorry. I can't figure out what you mean. Can you explain more detail?

**Comment by behaxe** [comment]
I want to go to my second tabbed bar view.
For instantiating my views, first i need to set the content view. In this case this is going to be my navigation controller, because it is the father. Then i instantiate the rootController.
I want to click on the User Image of the SideMenuController and go to my Second TabBarView.

My problem is that when i instantiate the father of the views, i must tell him that his tab bar controller (son) has to be instantiated with the second index.

Actually I can only present the first view of the tab bar controller. I have called it Home Controller.

(Excuse my English 😆 )

**Comment by kukushi** [comment]
Oh, I see.
You can retrieve the navigation controller from the `sideMenuController` via the `contentViewController`. Then, get the child tab bar controller from the navigation controller. Finally, switch the view controller index of the tab bar controller. And all the above  can be done on the action triggered by the view in the side menu.

**Comment by behaxe** [comment]
I resolve it via Notifications, but your time is so appreciated. Thanks for it. 
Keep contributing to the Swift Dev World!
👍

**Comment by lukeirvin** [comment]
Possible to see an example of this? Or just some pseudo code? I'm stuck on this problem.
