### ISSUE TITLE
iPhone XS issue with background image

### ISSUE THREAD

**Issue by mhamzasani** [kukushi/SideMenu#63]
Hi. The Sidemenu works good with iPhone 7,8 etc. But when it comes to iPhone XS.. the side menu background UIImage shows on the root controller.
![Screenshot 2019-06-04 at 10 43 44 AM](https://user-images.githubusercontent.com/37930382/58854296-4c131680-86b6-11e9-9250-510ec3c9aaa9.png)

**Comment by kukushi** [comment]
I think it's a layout issue. 
Using Visual Hierarchy debugger will provide a better vision.

**Comment by mhamzasani** [comment]
Thanks mate!
