### ISSUE TITLE
right direction not working.

### ISSUE THREAD

**Issue by jameszasod** [kukushi/SideMenu#65]
Code: https://user-images.githubusercontent.com/13145084/59599009-b05abf00-9127-11e9-8bd1-c3f1bde5ca6e.png

Display: https://user-images.githubusercontent.com/13145084/59599010-b0f35580-9127-11e9-8563-604bc0e0237b.png

**Comment by kukushi** [comment]
@jameszasod Thanks for your feedback. I will check it soon.

**Comment by kukushi** [comment]
@jameszasod You need to call `configureUI()` before the sidemenu appeared. `AppDelegate` should be a neat place.
