### ISSUE TITLE
Menu shifted left because origin shifted is -112.5

### ISSUE THREAD

**Issue by iDimka** [kukushi/SideMenu#66]
Hi there,

The control is nice! 
Cannot fix the next problem: Instantiated from a code. Menu shifted left because origin shifted is -112.5, you can see the last work of phrase -  "Report a problem". Also, menuViewController has the same width as the UIScreen.main

![Screen Shot 2019-06-24 at 1 04 05 AM](https://user-images.githubusercontent.com/931831/59993051-b74c6a80-961c-11e9-8900-a8cce8ea442e.jpg)
![Screen Shot 2019-06-24 at 1 13 49 AM](https://user-images.githubusercontent.com/931831/59993196-5bceac80-961d-11e9-8da1-13ec4b6f34f9.jpg)

**Comment by iDimka** [comment]
Fix for me:
![Screen Shot 2019-06-24 at 1 35 31 AM](https://user-images.githubusercontent.com/931831/59994043-69d1fc80-9620-11e9-872d-c8d59516fb41.jpg)

**Comment by anonrig** [comment]
Is there a fix to this without actually modifying the pod?

**Comment by anonrig** [comment]
@kukushi

**Comment by kukushi** [comment]
@iDimka @anonrig can you providing a demo or sample code for reproducing this problem?

**Comment by ahbou** [comment]
I have the same issue when instantiating from code.
I think the origin shouldn't change instead adjust the width.

**Comment by ahbou** [comment]
Here's a fix without patching the pod: Make your tableview's width equal to `SideMenuController.preferences.basic.menuWidth`

```
tableView.snp_makeConstraints { make in
        make.top.bottom.right.equalToSuperview()
       make.width.equalTo(SideMenuController.preferences.basic.menuWidth)
}
```

**Comment by nassifbasheer** [comment]
I am facing the same issue with the side menu instantiated via code

**Comment by nassifbasheer** [comment]
any fix for this issue

**Comment by ahbou** [comment]
@nassifbasheer did you try my fix above? I'm instantiating via code too.

The implementation of this library is **wrong** it shouldn't shift the view's origins.

**Comment by kukushi** [comment]
@nassifbasheer @ahbou 
It's the expected behavior, you need to layout the menu controller starting from `screen Width - menu width`(check out example storyboard for more information).

**Comment by ahbou** [comment]
Thanks @kukushi. In that example the Menu's view is shifted and starts at `{65,0}`.
IMHO it shouldn't, the superview should be resized to fit `menu width`
