### ISSUE TITLE
Crash iOS 13 on Real Device

### ISSUE THREAD

**Issue by FlorianBasso** [kukushi/SideMenu#67]
NSInternalInconsistencyExceptionfunction signature specialization <Arg[0] = Dead> of static (extension in SideMenuSwift):__C.UIWindow.sb.getter : __C.UIWindow?

App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.

I think the issue is here `static var sb: UIWindow?` on StatusBar.swift file.

**Comment by kukushi** [comment]
The status bar window has gone in iOS 13. I have to found another way to animate the status bar.

**Comment by jmoia** [comment]
Hi Kukushi, just seeing if you've already started working on a fix for iOS 13, or if I should start working on it...I'll probably just comment out and make a quick fix because I just use a static bar.

**Comment by kukushi** [comment]
@jmoia Beta sdk may change from time to time, so I will fix it on some later betas.

**Comment by iMostfa** [comment]
same, problem 
waiting for fix

**Comment by lucascorrea** [comment]
Hi @kukushi We are close to the release of iOS 13, would have as a branch with a workaround? Thanks

**Comment by hiroshi12465643** [comment]
I had to check this so I just commented out some codes related to Status Bar.
BasicTransitionAnimator worked with xcode11 beta5 & ios13. I haven't checked more than that.

https://github.com/hiroshi12465643/SideMenu/blob/06a773af044bbea084ba9f1eda80d05d50e812bb/SideMenu/SideMenuController.swift

**Comment by kukushi** [comment]
Guys, checkout branch `ios13` for a workaround.

**Comment by armydons** [comment]
@kukushi I can't accessible ios13 branch for a workaround.
Specify the link for that

**Comment by kukushi** [comment]
> @kukushi For which cases we getting that crash.

When the `statusBarBehavior` is not `.none`.

**Comment by kukushi** [comment]
Version 2.0.2 is released for a workaround. I will keep looking for an alternative way to archive the animation on iOS 13.

**Comment by haidukstore** [comment]
@kukushi i have the same problem even if i select .none . How fix it? version 2.0.2

**Comment by kukushi** [comment]
@haidukstore Can you post more detail error description?

**Comment by haidukstore** [comment]
@kukushi sorry, it's new xcode has some lag, after reload ".none" value work perfect

**Comment by JayeshMardiya** [comment]
I am getting crashed when I'm trying to fetch `foregroundView` using `UIApplication.shared.value(forKey: "statusBar")`

**Comment by adriaros** [comment]
I had the same error: "App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead"

The problem is that uploading Xcode 11 and iOS 13 you cannot use UIApplication.shared.value(forKey: "statusBar").

**Comment by dotWasim** [comment]
I have same problem

**Comment by kukushi** [comment]
@dotWasim Can you try again with a clean build?

**Comment by busu90** [comment]
What exactly should be set to .none and where? I'm still getting the crash with v2.0.2

**Comment by kukushi** [comment]
> @kukushi What exactly should be set to .none and where? I'm still getting the crash with v2.0.2

Does it still crash with a clean build?

**Comment by dotWasim** [comment]
@kukushi yes, It still crash

**Comment by kukushi** [comment]
@dotWasim @busu90  Would you mind sharing a screenshot when the breakpoint hitting the crash (probably in the `StatusBar.swift`)?

**Comment by busu90** [comment]
@kukushi It actually started to work for me after multiple cleans

**Comment by usahun** [comment]
@kukushi I have the same issue.
 App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.' please help thank you

**Comment by Bhavesh091** [comment]
```
        if #available(iOS 13, *) {
            return UIApplication.shared.windows.first { $0.isKeyWindow }
        } else {
            return UIApplication.shared.keyWindow
        }
        
//        return UIApplication.shared.value(forKey: s+b+w) as? UIWindow
```
