### ISSUE TITLE
Bug when swiped on Navigation bar

### ISSUE THREAD

**Issue by rahulbbit** [kukushi/SideMenu#69]
Side menu opens when swiped from NaviagtionBar when the viewcontroller is pushed

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11924067/61167857-25bc8280-a562-11e9-8a3d-5d586d0ce986.gif)

**Comment by kukushi** [comment]
I did reproduce this bug.
It only happens when user swiping on the navigation bar which is unusual.

**Comment by dheerajdex** [comment]
> Side menu opens when swiped from NaviagtionBar when the viewcontroller is pushed
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11924067/61167857-25bc8280-a562-11e9-8a3d-5d586d0ce986.gif)

How to install version 2.0.2.
I have install version 2.0.0 through cocoapod

**Comment by shraddha009** [comment]
Just write down below line in your viewdidload method of your contentView.
  self.navigationController?.interactivePopGestureRecognizer!.isEnabled = false

**Comment by rahulbbit** [comment]
@shraddha009 , this will disable swipe back to get back to previous controller, which is a default functionality of iOS to go back

**Comment by shraddha009** [comment]
> @shraddha009 , this will disable swipe back to get back to previous controller, which is a default functionality of iOS to go back

Yes it will but just for one screen resolving the major bug of sidemenu
