### ISSUE TITLE
Problems with swipe to delete in UITableView and support in RTL

### ISSUE THREAD

**Issue by Idomo** [kukushi/SideMenu#7]
Hi,
I just downloaded the library (what was very easy, surprisingly) and I'm facing 2 problems:
1) Swipe to delete in UITableView is not working at all because the menu is opening on swipe from everywhere on the screen (it should be only on the area that close to the menu side, for example, 20px).

2) The menu doesn't supporting RTL languages, it's stay on right/left in any language, what makes bad UI/UX for the RTL languages' speakers (and I'm sure a little if could fix it). 

Thanks,
Ido.

**Comment by kukushi** [comment]
Thanks for using.

1. I will take a closer look on it.
2. Maybe we can change the side menu direction according to the layout direction?
We can get the diirection from the system:
```
let attribute = view.semanticContentAttribute
let layoutDirection = UIView.userInterfaceLayoutDirectionForSemanticContentAttribute(attribute)
```

**Comment by Idomo** [comment]
@kukushi 
1. You can take a look on this library: https://github.com/arturdev/AMSlideMenu
They have took care on this as it mentioned here: https://github.com/arturdev/AMSlideMenu#ideas
Maybe it will help you to think about solution for this problem. 

2. Yes, it should be simple.
It will be nice if you'll add `SideMenuController.preferences.basic.direction = .auto` and also add this as default (so you can say that the library is full supporting AutoLayout)

**Comment by kukushi** [comment]
@Idomo 
Great suggestions!
I will implement that when I grab some time.
Maybe adding a new option like `recognizeSemanticContentLayoutDirection: Bool` will be a better solution.  It can apply to the default `right` direction, too.

**Comment by Idomo** [comment]
Hi @kukushi, There is some progress with what we talked about?
I'd like to start using the library and create the menu, but I can't do that while those problems are still happen...

**Comment by kukushi** [comment]
@Idomo 
Yeap, You can test it on the `develop` branch.

I had checked the AMSlideMenu's implementation. AMSlideMenu handles the panning via many conditions with the panning directions and the view on touching, like `UISlider` or `UITableViewCell`. IMO, it's too ad-hoc and only work on certain cases.

Therefore, I simply disable the pan gesture recognizer whenever there is another gesture recognizer going on. As a result, it would prevent the pan gesture recognizer from recognized when touching upon the scroll view.

**Comment by kukushi** [comment]
@Idomo 
It's now shipped with 0.4.1.

**Comment by Idomo** [comment]
@kukushi 
The auto direction works great!
I'm waiting for the swipe fixing, it's still very important part in the iOS UI/UX as you know and it's not impossible thing to do as we saw in the library that I mentioned before (https://github.com/arturdev/AMSlideMenu#ideas)

**Comment by kukushi** [comment]
@Idomo 
AMSlideMenu's approach is too ad-hoc, that's if we want to support both swipes right to reveal the menu and swipe left to delete the cell, we have to add many conditions to handle this case. The problem is, if we want to handle more gesture collision cases, we need to add more conditions. There will always be some cases that we can't handle, like custom `UIScrollView` subclass.  Thus, I may not change the current approach until there is a generic approach to handle all this stuff.

As for the `SideMenuController.preferences.basic.supportedOrientations`, Your point did make sense. My consideration is most apps nowadays are `portrait`, so I choose it as the default value. If I changed the value to `allButUpsideDown `, it may break the behavior of apps which is using this framework. So, I will keep it unchanged.

**Comment by Idomo** [comment]
@kukushi  I think you should mention this explanation in `README.md` file, it took me a while to find this preference as the one that prevent from my app to showing in another orientations except `portrait`.
You wort (by mistake I'm guessing) `SideMenuController.preferences.basic.enablePanGesture` twice and didn't mentioned the `SideMenuController.preferences.basic.supportedOrientations` option in the `Preferences` section (https://github.com/kukushi/SideMenu#preferences)

**Comment by kukushi** [comment]
@Idomo Sorry. I will update the readme.

**Comment by Ashtan25** [comment]
Can You please share the code for RTL. What exactly I have to do?? Please asap

**Comment by Idomo** [comment]
@Ashtan25 code of what part? the library should support it with the setting `shouldRespectLanguageDirection = true`

**Comment by Ashtan25** [comment]
please tell me where are you putting the following code cz its not working in my code

**Comment by Ashtan25** [comment]
can you please share the demo code if you have it

**Comment by Ashtan25** [comment]
Sorry guys its working perfectly sorry to bother you anyway. Thanks for the library

**Comment by JhonnyTawk** [comment]
@Ashtan25 can you provide me with some example I have the same issue as yours.
Thank you
