### ISSUE TITLE
iOS 13 Crash on 'statusBarWindow'

### ISSUE THREAD

**Issue by vtsourcecode** [kukushi/SideMenu#75]
The undocumented code to get the statusBarWindow is causing a fatal error and crashing the app with this message in the console.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'

**Comment by vtsourcecode** [comment]
This method:

static var sb: UIWindow? {
        // We use a non-public key here to obtain the `statusBarWindow` window.
        // We have been using it in real world app and it won't be rejected by the review team for using this key.
        let s = "status", b = "Bar", w = "Window"
        return UIApplication.shared.value(forKey: s+b+w) as? UIWindow
    }

**Comment by kukushi** [comment]
@vtsourcecode Please check out the latest version.

**Comment by vtsourcecode** [comment]
Thanks, just did that and problem solved.
