### ISSUE TITLE
SideMenu not working in iOS 13

### ISSUE THREAD

**Issue by nileshjaiswal16** [kukushi/SideMenu#77]
Please help me my sidemenu not working in iOS 13

**Comment by kukushi** [comment]
Nobody can help if you don't describe your problem.

**Comment by nileshjaiswal16** [comment]
[UIApplication sharedApplication].statusBarFrame deprecated in iOS 13 that's why application crashing when tap on hamburger menu.

**Comment by kukushi** [comment]
@nileshjaiswal16 Updating should solve your issue.

**Comment by cdstamper** [comment]
@nileshjaiswal16 this is fixed in the 2.0.2 release, you can try `pod repo update` if you're not seeing that version available
