### ISSUE TITLE
View doesn't display correctly

### ISSUE THREAD

**Issue by itchix** [kukushi/SideMenu#8]
Hello,

First thanks for your library. I've got some issue tu display the drawer. 
I used the library programmatically.
This is the hierarchy of my view controllers : 
UINavigationController -> UIRootCollectionViewController -> (DrawerViewController, ContentVieController)

![screen shot 2018-07-04 at 09 59 24](https://user-images.githubusercontent.com/2846894/42264942-6b2ae260-7f72-11e8-8334-2f54cf9a3b42.png)

![screen shot 2018-07-04 at 09 59 33](https://user-images.githubusercontent.com/2846894/42264947-6e1133e4-7f72-11e8-992c-cf7ff9957bc0.png)

![screen shot 2018-07-04 at 10 05 24](https://user-images.githubusercontent.com/2846894/42264960-751d2bb6-7f72-11e8-9da1-76119b13c10e.png)

![screen shot 2018-07-04 at 10 05 34](https://user-images.githubusercontent.com/2846894/42264962-77ce3698-7f72-11e8-9591-e799fe6cce31.png)

As you can see there is a "gap" between the root and the content / drawer. The content and the drawer are not sticked to the top of the root view.
To fix it i've change in contentFrame() and sideMenuFrame() functions the `baseFrame` variable (see comment below).
I don't really know if it's the good way, but it works.

Thanks

**Comment by itchix** [comment]
``` swift 
    private func sideMenuFrame(visibility: Bool) -> CGRect {
        let position = preferences.basic.position
        var baseFrame = UIScreen.main.bounds
        switch position {
        case .above, .sideBySide:
            if visibility {
                baseFrame.origin.x = preferences.basic.menuWidth - baseFrame.width
            } else {
                baseFrame.origin.x = -baseFrame.width
            }
            let factor: CGFloat = preferences.basic.direction == .left ? 1 : -1
            baseFrame.origin.x = baseFrame.origin.x * factor
            return baseFrame
        case .under:
            return baseFrame
        }
    }
    
    private func contentFrame(visibility: Bool) -> CGRect {
        let position = preferences.basic.position
        var baseFrame = UIScreen.main.bounds
        switch position {
        case .above:
            return baseFrame
        case .under, .sideBySide:
            if visibility {
                let factor: CGFloat = preferences.basic.direction == .left ? 1 : -1
                baseFrame.origin.x = preferences.basic.menuWidth * factor
            } else {
                baseFrame.origin.x = 0
            }
            return baseFrame
        }
    }
```

**Comment by kukushi** [comment]
Can this hierarchy meet your needs?

| - SideMenuController (also RootViewController)
| - - DrawerViewController
| - - UINavigationController 
| - - - - UIRootCollectionViewController
| - - - - - - ContentVieController

**Comment by itchix** [comment]
Indeed, it suits my needs and it works!
Thanks a lot :)
