### ISSUE TITLE
Xcode Version 11.0  and ios 13.0 reateStatusBarWithRequestedStyle App crash  , Please Provide support for that

### ISSUE THREAD

**Issue by Prashant961992** [kukushi/SideMenu#80]
* Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/UIApplication.m:5240

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'

**Comment by kukushi** [comment]
#67

**Comment by pujaadcolony** [comment]
I am also getting the same issue . Please help me out

**Comment by craigbooker** [comment]
I am getting this error as well. Any help appreciated.

**Comment by kukushi** [comment]
@pujaadcolony @Prashant961992 See the pinned issue, guys

**Comment by huukuntp1** [comment]
Hi @Prashant961992 , I also same with your issue. My issue related with Status Bar. can you check Status Bar component ?

**Comment by arjunguptha123** [comment]
i also  same issue  facing ,  how . to solve that issue

**Comment by ankit0409** [comment]
Is it any solution on this

**Comment by arjunguptha123** [comment]
Yes is there update particular Pod

**Comment by SebastianNYC** [comment]
does anyone have a solution? I have the same problem. But I don't access the StatusBar in my app.

**Comment by arjunguptha123** [comment]
just update the pod in our project .

**Comment by SebastianNYC** [comment]
It still doesn't work.

`import UIKit
import Firebase
import CoreData
import FBSDKCoreKit
import FBSDKLoginKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        FirebaseApp.configure()
        Database.database().isPersistenceEnabled = true // kann Dateien bereithalten bis internet wieder verfügbar ist
        FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)
        
        return true
    }

    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        
        let handled = FBSDKApplicationDelegate.sharedInstance().application(app, open: url, sourceApplication: options[UIApplicationOpenURLOptionsKey.sourceApplication] as! String?, annotation: options[UIApplicationOpenURLOptionsKey.annotation])
       
        return handled
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }


}`

**Comment by kukushi** [comment]
@SebastianNYC Which version of SideMenu are you using?
