### ISSUE TITLE
Terminating app on iOS 13

### ISSUE THREAD

**Issue by menayousif** [kukushi/SideMenu#82]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.

**Comment by kukushi** [comment]
#67 The issue was fixed in version 2.0.2.

**Comment by menayousif** [comment]
@kukushi 
I have installed 2.0.2, the app runs without any crashes. Although set statusBarBehavior = .fade or even statusBarBehavior = .hideOnMenu the side menu does not hide.

**Comment by kukushi** [comment]
@menayousif You are correct. 
The underlying implementation of the status bar on iOS 13 changed completely and It will need some more time to reimplement it.

**Comment by menayousif** [comment]
@kukushi 
okay thank you for your quick response and for your great effort
