### ISSUE TITLE
iOS 13 statusBar & statusBarWindow are deprecated

### ISSUE THREAD

**Issue by Karpyshyn** [kukushi/SideMenu#83]
Lib is calling statusBar and/or statusBarWindow. Buidling for iOS 13 cause crash with error
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.

Seems code need to be updated for using statusBarManager

**Comment by kukushi** [comment]
#67
