### ISSUE TITLE
Communication between two cached controllers

### ISSUE THREAD

**Issue by Tahia50** [kukushi/SideMenu#84]
I was looking through the example code where I wanted to pass value from "PreferencesViewController" -> "WorkWithOtherViewController" and vice versa by delegation. But I can not get the controller instances from the cache controllers. How can I achieve that?

**Comment by kukushi** [comment]
@Tahia50 There are many ways to communicate between different objects. The most straightforward way is to let them holding each other.

```swift
        sideMenuController?.cache(viewController: viewController1, with: "1")
        sideMenuController?.cache(viewController: viewController2, with: "2")
        viewController1.delegate = viewController2
```
