### ISSUE TITLE
Keep the tabbar showing in all views

### ISSUE THREAD

**Issue by JhonnyTawk** [kukushi/SideMenu#87]
I want to keep the tab bar visible in all views.
Even when I click on an item from the menu I want the Tabbar to be still visible how to achieve that?

**Comment by kukushi** [comment]
The description you provide is insufficient to understand your question.

Using the tab bar controller as the content view controller will meet your needs.

**Comment by Rj707** [comment]
@kukushi I am using tab bar controller as the content view controller, but the tab is not showing for me whenever I select any of the item of the Side Menu and Side Menu changes my content view controller.

**Comment by kukushi** [comment]
> @kukushi I am using tab bar controller as the content view controller, but the tab is not showing for me whenever I select any of the item of the Side Menu and Side Menu changes my content view controller.

When selecting an item in the Side menu, the content view controller will change and that means if the new view controller isn't a tab bar view controller, the tab bar will disappear.

**Comment by jatincdu** [comment]
@kukushi so what is the solution for tab bar disappear
