### ISSUE TITLE
Pass data between views

### ISSUE THREAD

**Issue by JhonnyTawk** [kukushi/SideMenu#88]
How to pass data between view controllers I am using 

`
sideMenuController?.cache(viewControllerGenerator: {
            mainStoryboard.instantiateViewController(withIdentifier: "pricingNav")
        }, with: "6")
`

I want when I click on an item in the menu to pass a value to that view controller 
for example :

`
            let instance = settingsStoryboard.instantiateViewController(withIdentifier: "LanguagesView") as? LanguagesView ?? LanguagesView()
            **instance.name = "New Name"**
            navigationController?.pushViewController(instance, animated: true)
`

How to achieve that.

Thank you

**Comment by kukushi** [comment]
Check out #84  for more information.

**Comment by JhonnyTawk** [comment]
@kukushi  I don't wanna use delegate 

```
let instance = settingsStoryboard.instantiateViewController(withIdentifier: "LanguagesView") as? LanguagesView ?? LanguagesView()

 **instance.name = "New Name"**

 navigationController?.pushViewController(instance, animated: true)
```

I want something similar to that
