### ISSUE TITLE
viewdidLoad()

### ISSUE THREAD

**Issue by milap-eww** [kukushi/SideMenu#9]
want `viewdidload()` to be called every-time it selects a viewcontroller from sidemenu

**Comment by kukushi** [comment]
If you don't use the caching and initializes a new view controller when switching content, then the `viewDidLoad()` would be called as you wish. But it is actually not a very good practice, I would recommend you using the `viewDidAppear` as alternatives.

**Comment by milap-eww** [comment]
But how, can you give me an example for that?

**Comment by kukushi** [comment]
Let the `viewDidLoad` called each time when selected:

    sideMenuController.contentController = YourViewController()

----

You can use a Bool property to control some part of the `viewDidAppear` to be called only once.
