### ISSUE TITLE
Reveal Menu not working from presented anotherViewController

### ISSUE THREAD

**Issue by Adakhan** [kukushi/SideMenu#92]
I send data to another tableView (ScheduleTableVC)

```
        let navigation = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SchedulePage") as! UINavigationController
        let vc = navigation.viewControllers.first as! ScheduleTableVC
        vc.text = ""
        self.present(navigation, animated: true, completion: nil)
```

But in ScheduleTableVC 
```
        self.sideMenuController?.revealMenu()
````
not working

**Comment by JhonnyTawk** [comment]
same issue.

**Comment by Adakhan** [comment]
Solve it with this

        let navigation = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SchedulePage") as! UINavigationController
        let vc = navigation.viewControllers.first as! ScheduleTableVC
        vc.text = ""
        
        sideMenuController?.setContentViewController(to: navigation, animated: false, completion: nil)
