### ISSUE TITLE
PanGesture to reveal menu stop working in second viewControler inside NavigationControler

### ISSUE THREAD

**Issue by sneves79** [kukushi/SideMenu#95]
Hello,

In sidemenu i have a button updating contentViewControler width a UINavigationControler, function below:

```
    @IBAction func openCategory(_ sender: UIButton) {
        let storyboard = UIStoryboard(name: "Category", bundle: nil)
        let vcCat = storyboard.instantiateViewController(withIdentifier: "catNavigation") as! UINavigationController
        sideMenuController?.contentViewController = vcCat
        sideMenuController?.hideMenu()
    }
```

It opens correctly and show the NavigationControler with is root UiViewControler, and panGesture works fine and reveals/hide the side menu on swipe

In NavigationControler if i do a segue to the second UIViewControler i want to open, code below:

`performSegue(withIdentifier: "toProductsSelection", sender: self)`

It's opens correctly, i no longer can swipe to reveal/hide side menu!

But if i run, `sideMenuController?.revealMenu()` it works fine.

Any input why the panGesture stop working? 

  ##Thanks

**Comment by kukushi** [comment]
@sneves79 
In fact, that is implemented by design.  Inside the navigation stack, swipe to pop is a more expected result than revealing the side menu.

**Comment by sneves79** [comment]
@kukushi 
Thanks for the input.
Ok, i understand. It's the correct behaviour.
Ty
