### ISSUE TITLE
Question about setting segues in the IB

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [kukushi/SideMenu#99]
Hi,

I created the setup for the menu all from the storyboard. It has 3 content view controllers.

![Screenshot 2019-12-21 at 21 37 25](https://user-images.githubusercontent.com/2551877/71310438-32f76a80-243a-11ea-9d0a-0e0e9851a8be.png)

![rsz_simulator_screen_shot_-_iphone_11_pro_-_2019-12-21_at_213425](https://user-images.githubusercontent.com/2551877/71310472-88337c00-243a-11ea-847a-170928442389.png)

The initial view controller and the menu shows up without a problem.

My question is how do I setup segues from the menu for the rest of the content view controller in the IB? My menu is a static table view controller. So I'd prefer if I could hook up segues from the cells to other view controllers within the storyboard itself.

Is that possible? Since the example project only shows how to wire up the initial view controller and doing the rest in code, I can't figure out how to do it.

**Comment by kukushi** [comment]
@Isuru-Nanayakkara Using segue to change content view controller is not yet supported.
